version: '3.8'
services:
  auth-client-dev:
    image: auth-client-dev-image
    container_name: auth-client-dev-container
    # stdin_open: true
    # tty: true
    build:
      context: ./client
    ports:
      - "8000:8000"
    volumes:
      - ./client/src:/app/src
    environment:
    - CHOKIDAR_USEPOLLING=true # This is for Windows users
    env_file:
      - ./client/.env
    depends_on:
      - auth-server-dev
    networks:
      - client-side
  auth-server-dev:
    image: auth-server-dev-image
    container_name: auth-server-dev-container
    build:
      context: ./server
    ports:
      - "8001:8001"
    volumes:
      - ./server:/app
    environment:
    - CHOKIDAR_USEPOLLING=true # This is for Windows users
    env_file:
      - ./server/.env
    networks:
      - client-side
      - server-side
    depends_on:
      - auth-db-dev
  # auth-db-dev:
  #   image: auth-db-dev-image
  #   container_name: auth-db-dev-container
  #   build:
  #     context: ./database
  #   ports:
  #     - "8002:8002"
  #   volumes:
  #     - ./database:/app
  #   environment:
  #   - CHOKIDAR_USEPOLLING=true # This is for Windows users
  #   env_file:
  #     - ./database/.env
  #   networks:
  #     - server-side

networks:
  client-side: {}
  server-side: {}