version: '3.8'
services:
  services:
    auth-client-dev:
      image: auth-client-dev-image
      container_name: auth-client-dev-container
      # stdin_open: true
      # tty: true
      build:
        context: ./client
      ports:
        - "3000:3000"
      volumes:
        - ./client:/app
      environment:
      - CHOKIDAR_USEPOLLING=true # This is for Windows users
      env_file:
        - ./client/.env
      # depends_on:
      #   - auth-server-dev
